### ISSUE TITLE
TypeError: ChatTypeFilter() takes no arguments.

### ISSUE THREAD

**Issue by globalwa** [MasterGroosha/aiogram-3-guide#27]
Глава "Фильтры и мидлвари", версия aiogram — 3.0.0b7. 
Ошибка:

> Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    from handlers import group_games
  File "...\handlers\group_games.py", line 10, in <module>
    ChatTypeFilter(chat_type=["group", "supergroup"])
TypeError: ChatTypeFilter() takes no arguments

Сработал данный вариант:

```
class ChatTypeFilter(Filter):
    def __init__(self, chat_type: Union[str, list]) -> None:
        self.chat_type = chat_type
    
async def __call__(self, message: Message) -> bool:
        if isinstance(self.chat_type, str):
            return message.chat.type == self.chat_type
        else:
            return message.chat.type in self.chat_type
```

**Comment by MasterGroosha** [comment]
Привет! Спасибо, исправил в 5442786d4bb479ba7e60b414647dcb093fc6c2f0
